# Main Ansible inventory file
#
# Copyright 2022 林博仁(Buo-ren, Lin) <Buo.Ren.Lin@gmail.com>
# SPDX-License-Identifier: CC-BY-SA-4.0
all:
  hosts:
    test-vm:
      ansible_host: __REDACTED__
      ansible_ssh_private_key_file: ~/.ssh/brlin-aws-default2022.pem
      ansible_user: ubuntu
